version: '3.4'

services:
    intel-cam:
        build:
            context: .
            dockerfile: Dockerfile-intel-cam
        environment:
          - GOOGLE_APPLICATION_CREDENTIALS
          - SERVER_TO_DEPTH_CAM_SUBSCRIPTION
          - DEPTH_CAM_TO_SERVER_TOPIC
          - QR_X11_NO_MITSHM=1
          - QT_GRAPHICSSYSTEM=native
          - STORAGE_BUCKET
          - DISPLAY=:1
        privileged: true
        cap_add:
            - ALL
        image: intel-cam-image
        container_name: intel-cam-container
        command: python hardware/pubsub_depth_cam_pull.py
        volumes:
          - .:/app
          - /dev:/dev
          - /lib/modules:/lib/modules
          - /tmp/.X11-unix:/tmp/.X11-unix
          
        stdin_open: true
        tty: true


