version: '3.4'

services:
    web: 
        build:
            context: .
            dockerfile: Dockerfile
        image: etl
        restart: always
        command: ./scripts/start-flask.sh -d 1
        depends_on:
          worker:
            condition: service_started
          database:
            condition: service_healthy

        environment:
            - GOOGLE_APPLICATION_CREDENTIALS
            - DATABASE_URL=postgresql://postgres_user:postgres_password@database:5432
            - PORT=5000
            - SECRET_KEY
            - FLASK_DEBUG=1
            - STORAGE_BUCKET
            - REDIS_URL
            - DIABETES_DATA_URL
            - SERVER_TO_DEPTH_CAM_TOPIC
            - DEPTH_CAM_TO_SERVER_SUBSCRIPTION
            - HEALTHCHECK_FAIL_NOTIFY_EMAIL
            - FOG_APP_PW
            - APP_EMAIL
            
        stdin_open: true
        tty: true
        ports:
            - "5002:5000"

        volumes:
            - .:/app
    worker:
        image: etl
        command: ./scripts/start-celery-worker.sh
        restart: on-failure
        depends_on:
            - database
            - redis
            - beat
            
        environment:
            - DATABASE_URL=postgresql://postgres_user:postgres_password@database:5432
            - FLASK_DEBUG=1            
            - GOOGLE_APPLICATION_CREDENTIALS    
            - SECRET_KEY
            - REDIS_URL
            - STORAGE_BUCKET            
            - SERVER_TO_DEPTH_CAM_TOPIC
            - DEPTH_CAM_TO_SERVER_SUBSCRIPTION
            - HEALTHCHECK_FAIL_NOTIFY_EMAIL
            - FOG_APP_PW
            - APP_EMAIL

        volumes:
            - .:/app
   
    beat:
        image: etl
        command: ./scripts/start-celery-beat.sh
        restart: on-failure
        depends_on:
            - database
            - redis

        environment:
            - DATABASE_URL=postgresql://postgres_user:postgres_password@database:5432            
            - FLASK_DEBUG=1        
            - GOOGLE_APPLICATION_CREDENTIALS            
            - SECRET_KEY
            - REDIS_URL
            - STORAGE_BUCKET
    redis:
        image: redis:5.0
        ports:
          - '6579:6379'
        volumes:
          - persistent_redis:/var/lib/redis/data
        
    database:
        environment:
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_password
        expose:
          - "5432"
        image: postgres:11.5
        ports:
          - "127.0.0.1:5445:5432"
        volumes:
          - persistent_database_postgres:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_user"]
          interval: 10s # Check every 10 seconds
          timeout: 5s   # Wait 5 seconds for the check to complete
          retries: 5    # Try 5 times before marking as unhealthy
          start_period: 10s # Give the container 10s to start before first check

volumes:
  persistent_database_postgres:
  persistent_redis:
