"""add_dummy_data

Revision ID: 24825bfd670b
Revises: 3b1b44f433bf
Create Date: 2020-12-14 00:44:53.190244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24825bfd670b'
down_revision = '3b1b44f433bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_data',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('random_data')
    # ### end Alembic commands ###
