"""add_pubsub_table

Revision ID: 7346fd820f47
Revises: 24825bfd670b
Create Date: 2020-12-21 02:24:24.775004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7346fd820f47'
down_revision = '24825bfd670b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pubsub_messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('publish_time', sa.DateTime(), nullable=False),
                    sa.Column('data', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pubsub_messages')
    # ### end Alembic commands ###
