"""add_unique_identifier

Revision ID: c8074206d00a
Revises: ebac28ee0d6a
Create Date: 2021-01-11 03:53:33.801780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8074206d00a'
down_revision = 'ebac28ee0d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pubsub_messages', sa.Column('unique_tag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pubsub_messages', 'unique_tag')
    # ### end Alembic commands ###
